### ISSUE TITLE
Weird random bug that is occuring during C++ object construction

### ISSUE THREAD

**Issue by keblu** [keblu/MSGARCH#11]
For weird reasons that I still don't know, at random time, the C++ object functionalities (tested on unc.vol) would only output NA or a random very low number such as 1e-254, but when the C++ object was recreated (via create.spec) the object would behave normally. This was happening randomly so I have implemented a work-around where the object would be recreated until the funcitonallities would behave normally (when this happen, we only need to recreate the object once).  This was also the reason why f.enhance.theta0 would sometime output an error with uniroot.

**Comment by ArdiaD** [comment]
Loop added to ensure that spec is well created; done by KB
