### ISSUE TITLE
No standard errors for parameter estimates

### ISSUE THREAD

**Issue by ishfaaq-k** [keblu/MSGARCH#25]
There are no standard errors for the parameter estimates. How to evaluate the significance of the parameters?

**Comment by ArdiaD** [comment]
1) read the vignette on SSRN
2) understand that MSGARCH can be estimated with MCMC which is much better than ML for parameter uncertainty estimation
3) use posterior sample to compute what you want: a) posterior mean, b) posterior median, c) posterior standard errors
