### ISSUE TITLE
Possible bug with AIC calculation

### ISSUE THREAD

**Issue by Timo09093440** [keblu/MSGARCH#29]
Thank you for building and maintaining this excellent package. I'm using it for my PhD, and I noticed a possible bug. A summary of a fitted model (with fit.mle) shows AIC < -2LL for single regime GARCH estimates, e.g. LL = -235.4 and AIC = 467. I tried to debug the AIC calculation, and it calls a function f.AIC, which calculates the traditional AIC = 2k - 2LL. But since the summary shows AIC < -2LL, the likelihoods must be from different sources. Indeed, the f.AIC function calculates the LL from the pdf of the fitted model, while, for example, the kernel function simply extracts the LL from the fitted model, which could explain the difference. It is my understanding that the kernel function is used to maximize the LL, which would imply the AIC calculation is off. If so, this bug perhaps also extends to other information criteria.

Finally, I'm using R 3.3.2 and the latest version of MSGARCH on CRAN 0.17.7. Please let me know if you need any other information.

**Comment by keblu** [comment]
The kernel function and the pdf function are a bit different. The kernel function include the likelihood of the parameter given some prior and the pdf is only the likelihood of the data given the paremeter (i.e., without considering the probability of the parameter given the prior distribution) . The AIC calculation should not include the likelihood of the prior which is why there is a slight difference.

**Comment by Timo09093440** [comment]
Hi keblu, I'm not disagreeing but I'm not sure I understand your explanation. Which LL is the "correct" one, i.e. the one I should be reporting? Do the priors matter when I've estimated the model with MLE? I'm asking because the original paper by Haas et al. (2004, p. 507, third line of Table 1), for example gives the LL as -6406.7, k as 4, and AIC as 12821. This works out precisely because -2*-6406.7 + 2*4 = 12821.4. It seems a priori strange to report AICs < 2LL, in particular because they will be central to my argument, so I need to understand in detail why they are what they are.

**Comment by ArdiaD** [comment]
1. fit.mle maximizes the kernel. => theta.hat
2. f.AIC reports the likelihood at theta.hat => this is the correct one
For computational reasons, we are using a kernel (combination of likelihood and priors) which is smoother than the likelihood alone. We should be consistent and report the "kernel" and "likelihood" values. Thanks for pointing this.
