### ISSUE TITLE
How to generate GARCH (1,1) series with simulation.

### ISSUE THREAD

**Issue by Farrukh1206** [keblu/MSGARCH#30]
I am try to generate GARCH (1,1) series with simulation, but with different parameter from default parameters. For example; alpha0 = 0.01 , alpha1 = 0.33, beta1 = 0.66, nu = 2.5.

**Comment by keblu** [comment]
spec = MSGARCH::create.spec(model = c("sGARCH"), distribution= "std") 

sim = MSGARCH::sim(spec, n = 1000, m = 1, theta = c(0.01, 0.33, 0.66, 2.5))

plot(sim)

**Comment by Farrukh1206** [comment]
I am estimating simulated series with MLE, Differential Evolution MLE, Metropolis Hasting and Adaptive Metropolis. While estimating the simulated series with different methodologies, it is found that after two to three series same series is generated, for example: 1st simulated series = 2nd/3rd simulated series. how can i solve this issue?

**Comment by keblu** [comment]
Do you have a sample code that so I can have a better grasp of the problem?

**Comment by ArdiaD** [comment]
@Farrukh1206 stop questions this way; this is suboptimal for all of us.
First read this: https://www.r-project.org/posting-guide.html
Thanks
