### ISSUE TITLE
Bayes Factors

### ISSUE THREAD

**Issue by robf-wustl** [keblu/MSGARCH#32]
Given the fit,bayes option, how can I use the output to calculate Bayes Factors (rather than using the approximation BF = log(BIC)) for model comparisons?

**Comment by ArdiaD** [comment]
Currently, there is no function to compute the BF. However, you could try to approximate the marginal likelihood and take the ratio. Marginal likelihood can be approximated using the posterior sample and the likelihood function.
NB: you could also consider using the predictive likelihood.
