### ISSUE TITLE
No results found in case bayesian VaR, 

### ISSUE THREAD

**Issue by Farrukh1206** [keblu/MSGARCH#34]
I found no convergence when i run this program. just by replacing "mle" with "bayes" i found no results, even i have tried it on fast computer.
ctr.bay=list(N.burn=500, N.mcmc=10000, N.thin=10, do.enhance.theta0 = TRUE)
fit = MSGARCH::fit.bayes(spec = spec, y = sp500, ctr = ctr.bay)
risk.bay = MSGARCH::risk(object = fit, level = c(0.95), ES = FALSE, do.its = TRUE)

kindly guide me.

**Comment by keblu** [comment]
In-sample risk measure for Bayesian chain and long series is very inefficient as of right now. The longer the chain and serie the worst it is. The package was first built with step ahead of estimation risk measure in mind so the in-sample option was kind of a add-on but not implemented efficiently. If you let it run long enough you will have results. We are working on a reimplementation probably in the coming weeks.
