### ISSUE TITLE
Repetition of simulation GARCH(1,1) for many time!

### ISSUE THREAD

**Issue by Farrukh1206** [keblu/MSGARCH#35]
you already guide me in generation of simulated series. Now, would it possible to repeat the process of simulation of GARCH(1,1) for lets suppose 1000 times, and then i want to estimate each series, and save the value of parameters. Would it possible?

**Comment by keblu** [comment]
If your read the doc you can see that: sim <- function(object, n, m, theta, burnin = 500) where n is the length of the simulation an m is the number of series simulated. For the estimation you can use a loop or more efficiently use the snowfall package for parallel processing.
