### ISSUE TITLE
Estimating GARCH(1,1) with Differential Evolution

### ISSUE THREAD

**Issue by Farrukh1206** [keblu/MSGARCH#39]
In earlier version of MSGARCH, when we estimate through ML approach, Differential Evolution algorithm was available, but now there is BFGS and others. 
I have had use MSGARCH package for the estimation in my thesis, with Differential Evolution. On the bases of this package, I set my objective and significance of thesis.

**Comment by keblu** [comment]
You can always use DEoptim with the argument OptimFUN in the control of FitML().

**Comment by keblu** [comment]
Plus the code for the custom optimizer is commented in the file Optimizers.R

**Comment by Farrukh1206** [comment]
# load data
data("SMI", package = "MSGARCH")

# create model specification
# MS(2)-GARCH(1,1)-Normal (default)
spec <- CreateSpec()

# fit the model on the data by ML
fit <- FitML(spec = spec, data = SMI, OptimFUN = DEoptim)
summary(fit)

I get following error, through this command

"Error in FitML(spec = spec, data = SMI, OptimFUN = DEoptim) : 
  unused argument (OptimFUN = DEoptim)"

**Comment by Farrukh1206** [comment]
# custom optimizer example
f_custom_optim <- function(vPw, f_nll, spec, data, do.plm){
 out <- stats::optim(vPw, f_nll, spec = spec, data = data,
                     do.plm = do.plm, method = "DEoptim")
 return(out)
}

set.seed(123)
fit <- FitML(spec, data = SMI, ctr = list(OptimFUN = f_custom_optim))

agian i obtian error, 

"Error in match.arg(method) : 
  'arg' should be one of “Nelder-Mead”, “BFGS”, “CG”, “L-BFGS-B”, “SANN”, “Brent”"

**Comment by keblu** [comment]
Of course, stats::optim do not have a DEoptim method. The example for the custom optimizer was... an example, you need to use the DEoptim package and create a custom optimizing function following the example structure  
```
f_custom_optim <- function(vPw, f_nll, spec, data, do.plm){
DEoptim stuff
}
```
This should work for you, you can tweak the function for your need:
```
require(MSGARCH)
require(DEoptim)
data(SMI)

f_DEoptim <- function(vPw, f_nll, spec, data, do.plm) {
  
  NP = 15 * length(vPw)
  
  mInitialPop = matrix(rep(vPw, NP) * rnorm(length(vPw) * NP) * 0.1, nrow = NP, byrow = TRUE)
  tmp <- DEoptim::DEoptim(f_nll, lower = rep(-10, length(vPw)), upper = rep(10, length(vPw)),
                              control = DEoptim.control(initialpop = mInitialPop, NP = NP, trace = TRUE, itermax = 500),
                              spec = spec, data = data, do.plm = do.plm)
  
  vPw_optim <- tmp$optim$bestmem
  dnllk <- tmp$optim$bestval
  names(vPw_optim) = names(vPw)
  
  out = list(par = vPw_optim, value = dnllk)
  
  return(out)
}

spec = CreateSpec()
fit.DE = FitML(spec = spec,data = SMI,ctr = list(OptimFUN = f_DEoptim))
```
