### ISSUE TITLE
 an error when using MCMC as the estimation method

### ISSUE THREAD

**Issue by LvouLeo** [keblu/MSGARCH#41]
I found an error when using MCMC as the estimation method.
> Error in { : task 1 failed - "chol(): decomposition failed"
> f_RCPP_adaptMCMC(theta0 = par0
>
#version infomation
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936 
[2] LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets 
[7] methods   base     

other attached packages:
[1] PerformanceAnalytics_1.4.3541 xts_0.9-7                    
 [3] zoo_1.8-0                     doRNG_1.6.6                  
 [5] rngtools_1.2.4                pkgmaker_0.22                
 [7] registry_0.3                  doParallel_1.0.11            
 [9] doSNOW_1.0.15                 snow_0.4-2                   
[11] iterators_1.0.8               foreach_1.4.3                
[13] MSGARCH_1.2                  

loaded via a namespace (and not attached):
[1] Rcpp_0.12.13     magrittr_1.5     fanplot_3.4.1   
 [4] xtable_1.8-2     lattice_0.20-34  stringr_1.2.0   
 [7] tools_3.3.3      grid_3.3.3       digest_0.6.12   
[10] Matrix_1.2-8     codetools_0.2-15 stringi_1.1.5   
[13] compiler_3.3.3   expm_0.999-2 

```
multi_day_VaR <- function(dur) {
  library(MSGARCH)
  data_est = All_dataset[c(dur),2]
  data_est = as.numeric(as.character(data_est))
  spec <- CreateSpec(variance.spec = list(model = c("gjrGARCH")),
                     distribution.spec = list(distribution = c("sstd")),
                     #distribution.spec = list(distribution = c("snorm")),
                     switch.spec = list(do.mix = FALSE, K = 2))
  ctr.bay = list(n.burn = 5000L, n.mcmc = 10000L, n.thin = 10L)
  out.bay = MSGARCH::FitMCMC(spec = spec, data = data_est, ctr = ctr.bay)
  sim = Sim(object = out.bay, n.ahead = 250, n.sim = 1)

  ret = t(apply(sim$draw, MARGIN = 2,FUN = cumsum))
  VaR = matrix(0,20,1)#1,5,10,20 days
  VaR[1,1] = quantile(ret[,1],probs = c(0.01)) # daily 
  VaR[2,1] = quantile(ret[,5],probs = c(0.01)) # weekly 
  VaR[3,1] = quantile(ret[,20],probs = c(0.01)) # monthly
  VaR[4,1] = quantile(ret[,60],probs = c(0.01)) # quarterly 
  VaR[5,1] = quantile(ret[,250],probs = c(0.01)) # yearly
  VaR[6,1] = quantile(ret[,1],probs = c(0.05)) # daily
  VaR[7,1] = quantile(ret[,5],probs = c(0.05)) # weekly
  VaR[8,1] = quantile(ret[,20],probs = c(0.05)) # monthly
  VaR[9,1] = quantile(ret[,60],probs = c(0.05)) # quarterly
  VaR[10,1] = quantile(ret[,250],probs = c(0.05)) # yearly

  #for n day ahead return
  VaR[11,1] = quantile(sim$draw[1,],probs = c(0.01)) 
  VaR[12,1] = quantile(sim$draw[5,],probs = c(0.01)) 
  VaR[13,1] = quantile(sim$draw[20,],probs = c(0.01)) 
  VaR[14,1] = quantile(sim$draw[60,],probs = c(0.01))
  VaR[15,1] = quantile(sim$draw[250,],probs = c(0.01))
  VaR[16,1] = quantile(sim$draw[1,],probs = c(0.05)) 
  VaR[17,1] = quantile(sim$draw[5,],probs = c(0.05)) 
  VaR[18,1] = quantile(sim$draw[20,],probs = c(0.05)) 
  VaR[19,1] = quantile(sim$draw[60,],probs = c(0.05))
  VaR[20,1] = quantile(sim$draw[250,],probs = c(0.05))
  VaR
}
#-----------------------------------------------------
#install.packages("doRNG")
#install.packages("doSNOW")
library(foreach)
library(doSNOW)
library(doParallel)
library(doRNG)

start.time <- Sys.time()

#setup parallel backend to use many processors

cl <- makeCluster(5, outfile="") #not to overload your computer
registerDoSNOW(cl) 

#parallel foreach loop
N=1
set.seed(123)
data_startpoint = 82

VaR_matrix = matrix(0,20,max(N))
VaR_matrix_MS = matrix(0,20,max(N))
tempMatrix = matrix(0,20,max(N))
############################################################
VaR_matrix_MS  <- foreach(i = 1:N,  .combine = 'cbind', .verbose=T ,.multicombine=T ) %dorng% { 
  set.seed(123)
  dur = (data_startpoint+i-1):(data_startpoint+1500+i-2)
  multi_day_VaR(dur)
}

#stop cluster
stopCluster(cl)
end.time <- Sys.time()
time.taken <- end.time - start.time
time.taken
```

**Comment by keblu** [comment]
I have made a fix on the github version if you want to try and install it.

  R > install.packages("devtools")
  R > require("devtools")
  R > devtools::install_github("keblu/MSGARCH", subdir="Package")

 For me there was no issue when I ran the code.

**Comment by LvouLeo** [comment]
Dear Mr. Keven BLUTEAU,  

   Sorry to bother you during weekend. Since I have update my MSGARCH package to V2.0 in an accident, and I have try to use the V1.3 in https://cran.r-project.org/src/contrib/Archive/MSGARCH/ which provide a slightly different numbers. So cloud you please send a copy of the keblu version 1.3? 

Thanks for your help! 

  Best Regards.

  Ou Lu

 

 

发件人: Keven Bluteau [mailto:notifications@github.com] 
发送时间: 2017年10月24日 21:24
收件人: keblu/MSGARCH <MSGARCH@noreply.github.com>
抄送: LvouLeo <stu116513@mail.uni-kiel.de>; Author <author@noreply.github.com>
主题: Re: [keblu/MSGARCH] an error when using MCMC as the estimation method (#41)

 

I have made a fix on the github version if you want to try and installed it.

R > install.packages("devtools")
R > require("devtools")
R > devtools::install_github("keblu/MSGARCH", subdir="Package")

For me there was no issue when I ran the code.

**Comment by keblu** [comment]
Previous version of the package are in https://github.com/keblu/MSGARCH/tree/master/bin. I think it is the same as the one on CRAN but I might be wrong. In any case, these are the only release we have.

**Comment by LvouLeo** [comment]
Dear Mr. Keven BLUTEAU,  

  Thanks for your help. But it still not provide the same result. 

  Best Regards.

  Ou Lu

 

 

发件人: Keven Bluteau [mailto:notifications@github.com] 
发送时间: 2017年11月19日 13:52
收件人: keblu/MSGARCH <MSGARCH@noreply.github.com>
抄送: LvouLeo <stu116513@mail.uni-kiel.de>; Author <author@noreply.github.com>
主题: Re: [keblu/MSGARCH] an error when using MCMC as the estimation method (#41)

 

Previous version of the package are in https://github.com/keblu/MSGARCH/tree/master/bin. I think it is the same as the one on CRAN but I might be wrong. In any case, these are the only release we have.
