### ISSUE TITLE
Trace plots of MCMC, and values of MCMC.

### ISSUE THREAD

**Issue by Farrukh1206** [keblu/MSGARCH#42]
I have to plots the MCMC of bayesian, along with it i need these values as well for further analysis. In old version of MSGARCH I was able to do these steps but now it is hard for me.

**Comment by keblu** [comment]
The chain is in the variable par in the list you get after fitting data via FitMCMC which is clearly indicated in the documentation of the FitMCMC function. You can plot the chain as you see fit. 

Be mindful that this is a page for issues (mostly possible bugs) related to the MSGARCH package, not stackoverflow.
