### ISSUE TITLE
FitML function fails with an error

### ISSUE THREAD

**Issue by abon318** [keblu/MSGARCH#43]
@keblu 
I am trying to fit an MS GARCH model  on a vector y, however when the loop below reaches i=3 I get this R Error: $ operator is invalid for atomic vectors. The code I am using is the following:

    library(MSGARCH)
        fitmlnorm <- list()
        for (i in 1:3)
        {
          spec <- CreateSpec(variance.spec = list(model = c("sGARCH")), distribution.spec = list(distribution = c("norm")), switch.spec = list(K = i))
          fitmlnorm[[i]]<-FitML(spec, y)
        }

the numeric data of y can be found here:
[link](https://1drv.ms/u/s!As0vrfV8OFI_gY5i5fhTDbnxv90zYg)
From testing it out, the problem seems to be with the data y as with other vectors y the loop works without incident e.g. for the following vector: 
[link](https://1drv.ms/u/s!As0vrfV8OFI_gY5jgLqxjUcbZ7pWXQ)

**Comment by keblu** [comment]
This kind of error can happen when the optimization routine fail. Moreover, failure is often due to  scale of the data. The package has some preset assumption about the data. We expect something that looks like stock log-return * 100 (i.e., in percentage).

**Comment by abon318** [comment]
The data being used is infact pound exhange rate log returns *100.

Regards,
Anna Bonello

**Comment by keblu** [comment]
We now have a good idea of what is the problem, will try to push a fix asap. This comes from the starting value routine we have implemented.

 In the meantime you could either setup your own starting value FitML(spec, data, ctr = list(par0 = starting_parameter)) or use FitMCMC to calibrate your model. If you only want to use maximum likelihood estimation, you could also take the parameter mean of the MCMC chain given by FitMCMC as starting value for FitML.

**Comment by abon318** [comment]
Thank you. I chose another dataset for the time being which is working fine even with the implemented starting value routine. However do you still suggest to change the starting value routine?

On a very different note can you kindly explain why when extracting the state unconditional volatility you are multiplying by sqrt(250)?
sqrt(250) * sapply(ExtractStateFit(fit.ml), UncVol)

**Comment by abon318** [comment]
Thank-you for your reply. By any chance is there a way how I can extract the residuals after fitting a 2 regims MS GARCH model using MLE

**Comment by keblu** [comment]
You have the function conditional_volatility  <- **Volatility(fit)** that will extract the conditional volatility at each point in time in your sample. Then you can simply do: data/conditional_volatility to get the residuals.

**Comment by stephen15th** [comment]
Hey, just wondering if there is a solution to this? I am having the same problem with the fitML, but my data is in percentage log returns already.

**Comment by abzhaobo** [comment]
Just experimented with CRSP value weighted return data with the date range covering 1932.01-1936.12. If setting K=4 with raw return (i.e. not percentage), the error throws. If setting K=3 with percentage return, the error throws again.

So it may not be about whether using percentage return or not.

**Comment by ch-pg** [comment]
> You have the function conditional_volatility <- **Volatility(fit)** that will extract the conditional volatility at each point in time in your sample. Then you can simply do: data/conditional_volatility to get the residuals.

The residuals have close to unit standard deviation. But when I calculate the standard deviation of the residuals in each regime, they differ greatly, e.g. with one regime at 0.7 and the other at 1.6. 

Can anyone help explain this? I imagine that they would also have unit standard deviation, since the data in each regime is filtered by a GARCH model.
