### ISSUE TITLE
Model specification - regime constant

### ISSUE THREAD

**Issue by abon318** [keblu/MSGARCH#45]
I am trying to fit a 3 regime MS GARCH model using the following specification:
spec <- CreateSpec(variance.spec = list(model = c("sGARCH")), distribution.spec = list(distribution = c("std")), switch.spec = list( K = 3),constraint.spec = list(regime.const = c("nu"))) 

The MLE estimation works find but when I am using MCMC the following error is printed:

**Error in f_RCPP_adaptMCMC(theta0 = par0, acc_rate = 0.25, sigma = diag(length(par0)),  : 
  Evaluation error: 'names' attribute [17] must be the same length as the vector [16].**

This error has something to do with the constraint specification because when I remove it, it works fine. 

Can you kindly help.

**Comment by keblu** [comment]
Should be fixed now. Thanks.

**Comment by abon318** [comment]
Where can I download the updated package?

**Comment by keblu** [comment]
Look in the folder bin in the github repo. We keep all recent version of MSGARCH there. Look for v.2.2. You can then install it from the source. CRAN upload will come in later.

**Comment by abon318** [comment]
Yes I installed the package from the source but I keep getting this error "is not installed for 'arch = x64'"

**Comment by keblu** [comment]
you can also try devtools::install_github(repo = "keblu/MSGARCH", subdir = "Package")
