### ISSUE TITLE
How to plot smoothed probability for all possible states?

### ISSUE THREAD

**Issue by sugaxh** [keblu/MSGARCH#46]
I had this question when I tried to  import the code:
>spec<- CreateSpec(variance.spec = list(model = c("sGARCH")),distribution.spec = list(distribution = c("std")),switch.spec = list(do.mix = FALSE, K = 3))
> data("SMI", package = "MSGARCH")
> fit <- FitML(spec = spec, data = SMI)
> state <- State(object = fit)
> plot(state, type.prob = "smoothed")

but I only get "the smoothed probability for state3",I also want to get the plot for state2 and state1.How could I get them?
Please help me!Thank you~

**Comment by keblu** [comment]
They are plotted, it's just that each state get plotted one after the other so you only see the last one if you don't look at the plot history.

**Comment by sugaxh** [comment]
YES!I have found them.Thank you so much for helping me~
