### ISSUE TITLE
How to get FitMCMC model estimations？

### ISSUE THREAD

**Issue by Scienyu** [keblu/MSGARCH#47]
Hi keblu！I am using your package  fitting a markov switching Garch model and I want to compare this model with a Garch(1,1) model. So I want to know how to plot the msGARCH model on sample ponit? I'm looking forward to your reply，thank you！

**Comment by keblu** [comment]
What do you want to plot specifically? The in sample volatility ?

**Comment by Scienyu** [comment]
In fact, I am comparing the effects of GARCH (1,1) and two-state Markov switching GARCH-M model, so I want to plot a fig like c as shown in the following figure
![_20180606210442](https://user-images.githubusercontent.com/31590002/41039845-45d1ce08-69cd-11e8-864b-8a070d47d173.png)

**Comment by Scienyu** [comment]
Besides,  could you tell me how to plot the smoothed probability? I'm looking forward to your reply,thank you！

**Comment by ArdiaD** [comment]
We spent weeks writing the vignette:
http://dx.doi.org/10.2139/ssrn.2845809 
Read it; all is inside.
Thanks
