### ISSUE TITLE
devtools::check() with S3 method

### ISSUE THREAD

**Issue by keblu** [keblu/MSGARCH#5]
I just realized that the check function gives us warnings when S3 method are not consistent in parameters:

cdf(spec, x, theta, y, log, is.its) : call cdf_MSGARCH_SPEC
cdf(fit, x, log, is.its) : call cdf.MSGARCH_MLE_FIT or cdf.MSGARCH_BAY_FIT

will give a warning. I don't know if there is a way to suppress the warning without splitting the function in 2 (e.g., cdf_fit, cdf_spec)

**Comment by braverock** [comment]
S4  or Reference Classes allow dispatch on the class of the arguments.  S3 does not.  S3 can dispatch on the class of the first argument if the function is a generic.

For example, you could create a cdf.default function, and declare it as an S3 generic.

Then you would create methods

cdf.MSGARCH_SPEC
cdf.MSGARCH_FIT

note that all the arguments before dots must be the same for each method function, so looking at the example above, the cdf.default method could have a function signature something like

cdf.default(action,x,...)

or you could come up with some other method to make sure that the generic function signature makes sense.

You can't suppress warnings in R CMD check.  CRAN will reject on anything but a pristine check.
