### ISSUE TITLE
Is it possible to specify the lags in(G)ARCH models?

### ISSUE THREAD

**Issue by abzhaobo** [keblu/MSGARCH#50]
Sorry if this is not the place for asking questions. I'd like to know if it is possible to indicate the lags, for example, ARCH(1) or ARCH(2), GARCH(1,1) or GARCH(1,2) in the model selections? It seems that the arguments, 'sARCH', 'sGARCH' etc. fix the parameters to be ARCH(1) and GARCH(1,1), but there are no other arguments controlling the lags.

**Comment by keblu** [comment]
There is currently no way to add more lag. From our own experience, this is generally not necessary, at least for asset return.

**Comment by abzhaobo** [comment]
OK, thanks!
