### ISSUE TITLE
MSE and residual extraction from simulated data

### ISSUE THREAD

**Issue by JainVikas** [keblu/MSGARCH#51]
Hi Team,
Thanks for the superb work on this package.
I am trying to get the standard error, MSE from the package. 
I was able to get the residuals using  [this link](https://github.com/keblu/MSGARCH/issues/43#issuecomment-372157823)
"You have the function conditional_volatility <- Volatility(fit) that will extract the conditional volatility at each point in time in your sample. Then you can simply do: data/conditional_volatility to get the residuals."

Now I am trying to do the same from simulate object as I can see that it gives you the draw data and conditional_volatility of the simulated data.
```
#MCMC #100 Simulations 
sim.series<- simulate(object = spec, par = fit1$par, nahead= 214L, nsim = 2)
res_100_sim_vol1 = sim.series$draw/sim.series$CondVol[,,1]
mse_100_sim_vol1 = mean(res_100_sim_vol1^2)

res_100_sim_vol2 = sim.series$draw/sim.series$CondVol[,,2]
mse_100_sim_vol2 = mean(res_100_sim_vol2^2)

avg_mse_100_sim_vol= (mse_100_sim_vol1+mse_100_sim_vol2)/2
avg_mse_100_sim_vol
```

I want to confirm with you, if my understanding of getting this residuals and then using those to get MSE is correct. If not, can you redirect me to something else that might help?
Thanks

**Comment by keblu** [comment]
You can indeed get the standardized residual by dividing the data by the conditional volatility. Keep in mind that the model assumes that the mean of the data is 0.

However I am not sure why you would want to compute the mean of the squared standardized conditional volatility as you show in your code. If your goal is to compute the fitness of the model to your data, I would recommend computing the likelihood based AIC or BIC criterion for which we have function for it (AIC() and BIC() or DIC() for bayesian estimation).  

MSE in the context of volatility modeling is usually used when someone have an observable estimate of the volatility like realized volatility where one can compute the MSE using the squared difference between the estimated volatility via the model and the realized volatility.

**Comment by JainVikas** [comment]
Thanks for your input. 
I am computing the mean of the squared residuals obtained from simulated data not directly on the conditional volatility.
The aim is to compare the which model (MCMC or ML ) has better forecasting capability on my data in hand. Hence, I am trying to extract MSE for both models.
Once, I am able to extract MSE, I would expand the same for other datasets as well.

**Comment by keblu** [comment]
Take a look at

https://www.sciencedirect.com/science/article/pii/S0169207018300840

We use several measure of performance adequate for Risk/volatility forecasting for both MCMC and ML. Most of what you need to replicate are in the MSGARCH and GAS package.

**Comment by JainVikas** [comment]
thanks, found something similar to your first comment about MSE calculation
https://doi.org/10.1016/j.jfds.2016.06.001
