### ISSUE TITLE
Importance of Simultaneous Mean and Variance Estimation

### ISSUE THREAD

**Issue by acwc22** [keblu/MSGARCH#55]
Hi,

In EViews, it is possible for an ARMA-GARCH model to be estimated simultaneously in one-step which ensures estimates for both the conditional mean and variance are efficient. Given that MSGARCH does not consider the mean equation, I was wondering what effect this might have on conditional variance estimates if there was no feedback of the conditional variance to the original mean equation?

Kind regards,
Eric

**Comment by keblu** [comment]
The MSGARCH specification implemented in the MSGARCH package is the Haas et al. 2004 specification which makes the model only analytically tractable as long as no process is specified for the conditional mean. As our main focus was on modeling stock return which usually does not show AR or MA effect, we did not include a solution for estimating a mean equation in the package. 

There is some MSGARCH model that allows for ARMA processes for the mean equation. Most use Bayesian methods to estimate them. For example:

https://www.tandfonline.com/doi/full/10.1080/00036840802552379?src=recsys

**Comment by acwc22** [comment]
Thanks!
