### ISSUE TITLE
In-sample conditional volatility

### ISSUE THREAD

**Issue by acwc22** [keblu/MSGARCH#56]
In for example, a 2-regime MSGARCH model, using the Volatility() function generates a single column of data for the in-sample conditional volatility of the model at each time period. How is the conditional volatility at each time period calculated, because it doesn't seem to be a simple weighted average of the individual regime volatilities using filtered, smoothed, or predicted probabilities at each time period?

**Comment by keblu** [comment]
Its a weighted average of the individual regime **variance** using the predictive probabilities. Then the square root of the resulting variance gives the volatility.

**Comment by acwc22** [comment]
Thank you!
