### ISSUE TITLE
a problem in tgarch

### ISSUE THREAD

**Issue by kongqibuqingxin** [keblu/MSGARCH#57]
I am studying tGarch model by MSGARCH, but find out the estimated efficient are not similar as the simulation.  I also notice that the coeffecient should satisfy some constrains (in Ardia paper). Any other constraints?
![image](https://user-images.githubusercontent.com/57850964/69002236-c88e6000-08b8-11ea-81e2-c90796f04a08.png)

tgarchsim.s<- CreateSpec(variance.spec = list(model = "tGARCH"), switch.spec = list(K = 1)) 

par<-c(0.10,0.10,0.30,0.02)
sim <- simulate(object = tgarchsim.s, nsim = 1L, nahead = 1000L, nburn = 500L, par = par)

tgarchtextsim.ml <- FitML(spec = tgarchsim.s, data = sim$draw)

summary(tgarchtextsim.ml)

**Comment by keblu** [comment]
For the tGARCH, with exception of α_0,k > 0, α_1,k > 0, α_2,k > 0 and β_k ≥ 0 and the constraint above, there is no other constraint (we have an upper bound on parameter for optimization purpose but these are high).

I have tried with your setup and, indeed, you often get a very bad estimation. This is kind of random (depends on the simulation results).

I suspect that your parameter set does not obey the constraint above in that case or is very close to it. 

Here is an alternate test that I did:

```
require(MSGARCH)
data(SMI)
tgarchsim.s<- CreateSpec(variance.spec = list(model = "tGARCH"), switch.spec = list(K = 1))

tgarchtextsim.ml.1 <- FitML(spec = tgarchsim.s, data = SMI)

par = tgarchtextsim.ml.1$par
par

  alpha0_1   alpha1_1   alpha2_1     beta_1 
0.08689530 0.05768989 0.18283199 0.82426932

sim <- simulate(object = tgarchsim.s, nsim = 1L, nahead = 10000L, nburn = 5000L, par = par)

tgarchtextsim.ml.2 <- FitML(spec = tgarchsim.s, data = sim$draw)

summary(tgarchtextsim.ml.2)


Specification type: Single-regime
Specification name: tGARCH_norm
Number of parameters in variance model: 4
Number of parameters in distribution: 0
------------------------------------------
Fitted parameters:
         Estimate Std. Error  t value  Pr(>|t|)
alpha0_1   0.0817     0.0072  11.2725    <1e-16
alpha1_1   0.0563     0.0078   7.1738 3.647e-13
alpha2_1   0.1807     0.0155  11.6268    <1e-16
beta_1     0.8287     0.0070 118.1142    <1e-16
------------------------------------------
LL: -14546.547
AIC: 29101.0939
BIC: 29129.9353
------------------------------------------
```
The estimated parameters are very close to the true one in that case. 
Of course, the longer the simulation, the closer you will be to the true parameters.
