### ISSUE TITLE
A problem of backtesting

### ISSUE THREAD

**Issue by hpompom** [keblu/MSGARCH#58]
I using the code which in journal of Statistics Softsare to compare  ms2.gjr.std and ms2.gjr.sn
`models <- list(ms2.gjr_gjr.std,ms2.gjr_gjr.sn)
n.ots    <- 2000# number of out-of-sample evaluation
n.its    <- 1000 # fit sample size
alpha    <- 0.05 # risk Level
k.update <- 100  # estimation frequency

## Initialization
VaR   <- matrix(NA, nrow = n.ots, ncol = length(models))
y.ots <- matrix(NA, nrow = n.ots, ncol = 1)
model.fit <- vector(mode = "list", length = length(models))
sh.ret <- data.ret$`000001.ss`
# iterate over out-of-sample time
for (i in 1:n.ots) {
  cat("Backtest - Iteration: ", i, "\n")
  y.its    <- sh.ret[i:(n.its + i - 1)] # in-sample data
  y.ots[i] <- sh.ret[n.its + i]         # out-of-sample data
  
  # iterate over models
  for (j in 1:length(models)) {
    
    # do we update the model estimation
    if (k.update == 1 || i %% k.update == 1) {
      cat("Model", j, "is reestimated\n")
      model.fit[[j]] <- FitML(spec = models[[j]], data = y.its,
                              ctr = list(do.se = FALSE))
    }
    
    # calculate VaR 1-step ahead
    VaR[i,j] <- Risk(model.fit[[j]]$spec, par = model.fit[[j]]$par,
                     data = y.its,
                     n.ahead = 1,
                     alpha   = alpha,
                     do.es   = FALSE,
                     do.its  = FALSE)$VaR
  }
}
`
but it return Error in NextMethod("[<-") : replacement has length zero.

**Comment by ViniNazato** [comment]
Happening to me as well, was there any solution to this?
