### ISSUE TITLE
Issue with FitMCMC function throwing error

### ISSUE THREAD

**Issue by htes5** [keblu/MSGARCH#70]
Hello,

I am having an issue with the FitMCMC function. I am trying to use a csv with one column made up of historical Cocoa close prices to create a 2-regime ARCH model with a t-student distribution in both.

The following is the error I am getting when I run FitMCMC:
...
Error: $ operator is invalid for atomic vectors
In addition: Warning message:
In log((x[i, ] - lower)/(upper - x[i, ])) : NaNs produced

R script and csv used to load data:
...
[MSGARCH_script.txt](https://github.com/keblu/MSGARCH/files/6287225/MSGARCH_script.txt)
[20210407_CJ_close.txt](https://github.com/keblu/MSGARCH/files/6287228/20210407_CJ_close.txt)

**Comment by keblu** [comment]
Just checked your code and data. I think the fundamental problem is that you seem to feed the close price time series to the model. 

The MSGARCH model is not meant to take price level as input but (log)returns data  (or percentage changes). In that case you need to compute the return of time series. 

We also multiply that new serie by 100 such that a value of 1 mean 1% change, this is for numerical stability.

**Comment by ArdiaD** [comment]
@htes5 please read carefully manuals
