### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by drepalma** [keblu/MSGARCH#72]
I'm trying to install the package. But I'm getting the error below when I  try to load the package. Could someone help me please?
> library(MSGARCH)
Erro: package or namespace load failed for ‘MSGARCH’ in .doLoadActions(where, attach):
 error in load action .__A__.1 for package MSGARCH: loadModule(module = "MSgarch", what = TRUE, env = ns, loadNow = TRUE): Unable to load module "MSgarch": pacote 'Rcpp_precious_remove' não oferece a função 'Rcpp'
Além disso: Warning message:
package ‘MSGARCH’ was built under R version 4.0.5 

thank you in advance

**Comment by braverock** [comment]
it looks like you need to rebuild the package for your version of R.
